// task11-vue/one-piece-page/src/components/CommonItemsContainer.vue
<template>
    <div :id="Id" class="common-items-container">
                    <div class="common-items-container_content">
                        <div class="common-items-container_title">
                            <div class="common-items-container_title--main">
                                <span>{{title}}</span>
                            </div>
                            <div class="common-items-container_title-see-all">
                                <span>See all</span>
                            </div>
                        </div>
                        <CommonItemsContainerGridVue v-if="title==='Characters'" :type="title"></CommonItemsContainerGridVue>
                        <CommonItemsContainerGridVue v-if="title==='Islands'" :type="title"></CommonItemsContainerGridVue>
                        <CommonItemsContainerGridVue v-if="title==='Mist Objects'" :type="title"></CommonItemsContainerGridVue>
                    </div>
                </div>
</template>

<script>
    import CommonItemsContainerGridVue from './CommonItemsContainerGrid.vue'
    export default {
        name:"CommonItemsContainer",
        props:["Id", "title"],
        components:{CommonItemsContainerGridVue}
    }
</script>

<style scoped>

</style>

// task09-reactjs/one-piece-page/src/Components/CommonItemsContainer.js
import React, { Component } from 'react';
import CommonItemsContainerGrid from './CommonItemsContainerGrid';

export default class CommonItemsContainer extends Component{
    constructor(props){
        super(props)
    }
    render(){
        return(<div id={this.props.ID} className="common-items-container">
                    <div className="common-items-container_content">
                        <div className="common-items-container_title">
                            <div className="common-items-container_title--main">
                                <span>{this.props.title}</span>
                            </div>
                            <div className="common-items-container_title-see-all">
                                <span>See all</span>
                            </div>
                        </div>
                        {this.props.title==="Characters"? <CommonItemsContainerGrid type={this.props.title}></CommonItemsContainerGrid>:""}
                        {this.props.title==="Islands"? <CommonItemsContainerGrid type={this.props.title}></CommonItemsContainerGrid>:""}
                        {this.props.title==="Mist Objects"? <CommonItemsContainerGrid type={this.props.title}></CommonItemsContainerGrid>:""}
                    </div>
                </div>
          )
    }
}
