// task11-vue/one-piece-page/src/components/IslandContainerGridItem.vue
<template>
    <div class="island-container_grid_item"  :class="[mostrar && 'hideTablet', index>1 && 'hideMore']" >
        <img :src="img" alt="" />
        <div class="island-container_grid_item_descripcion">
        <b><span>{{name}}</span></b>
            <div class="island-container_grid_item_descripcion_region">
                <img style="width: 10px; height: 10px;" src="../assets/loc.svg" alt="" />
                <span>{{location}}</span>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "IslandContainerGridItem",
        props:["img", "name", "mostrar" , "index", "location"]
    }
</script>

<style scoped>

</style>

// task09-reactjs/one-piece-page/src/Components/IslandContainerGridItem.js
import React, { Component } from 'react';

import location from '../images/loc.svg'

const logoStyle={
    width:'10px',
    height: '10px'
}

export default class IslandContainerGridItem extends Component{
    constructor(props){
        super(props)
    }
    render(){
        return( <div className={`island-container_grid_item ${this.props.mostrar? '':' hideTablet'} ${this.props.index >1 ?'hideMore':''}`}>
                    <img src={this.props.img} alt="" />
                    <div className="island-container_grid_item_descripcion">
                    <b><span>{this.props.name} - {this.props.index}</span></b>
                    <div className="island-container_grid_item_descripcion_region">
                        <img
                        style={logoStyle}
                        src={location}
                        alt=""
                        />
                        <span>{this.props.location}</span>
                    </div>
                    </div>
                </div>)
    }
}
