// task11-vue/one-piece-page/src/components/LanguagesItem.vue
<template>
    <div class="languages_item " v-bind:class="text ==='English' && 'languages_item--selected'">
        <span class="hideDesktop"> {{text}}</span>
        <img v-if="text ==='English'" src="../assets/usa.svg" alt="" />
        <img v-else src="../assets/spain.svg" alt="" />

    </div>
</template>
<script>
    export default {
        name:"LanguagesItem",
        props:["text","url"]
    }
</script>

<style scoped>

</style>

// task09-reactjs/one-piece-page/src/Components/LanguagesItem.js
import React, { Component } from 'react';

import spanishIcon from '../images/spain.svg'
import englishIcon from '../images/usa.svg'
export default class LanguagesItem extends Component{
    constructor(props){
        super(props);
    }
    render(){
        return(
            <div className= {`languages_item ${this.props.Language === "English"? " languages_item--selected" : ""} `}>
                <span className="hideDesktop"> {this.props.Language}</span>
                <img src={this.props.Language === "English"? englishIcon : spanishIcon} alt="" />
            </div>
        )
    }
}
