// task11-vue/one-piece-page/src/components/MistObjectGridItem.vue
<template>
    <div class="mist-objects-container_grid_item">
        <img :src="img" alt="" />
        <div class="mist-container_grid_item_descripcion">
            <b><span>{{name}}</span></b>
            <span>{{description}}</span>
        </div>
    </div>
</template>

<script>
    export default {
        name: "MistObjectGridItem",
        props:["img", "name", "description"]
    }
</script>

<style scoped>

</style>

// task09-reactjs/one-piece-page/src/Components/MistObjectGridItem.js
import React, { Component } from 'react';

export default class MistObjectGridItem extends Component{

    constructor(props){
        super(props);
    }
    render(){
        return(<div className="mist-objects-container_grid_item">
                <img src={this.props.img} alt="" />
                <div className="mist-container_grid_item_descripcion">
                <span className       ="name">{this.props.name}</span>
                <span>{this.props.description}</span>
                </div>
            </div>)
    }
}
