// task09-reactjs/one-piece-page/src/App.js
import './App.css';
import MenuContainer from './Components/MenuContainer';
import MenuOptions from './Components/MenuOptions';
import SinopsisContainer from './Components/SinopsisContainer';
import SearchSection from './Components/SearchSection';
import CommonItemsContainer from './Components/CommonItemsContainer';
function App() {
  return (
    <>
     <MenuContainer></MenuContainer>
     <MenuOptions></MenuOptions>
     <SinopsisContainer></SinopsisContainer>
     <div className="space-under-absolute"></div>
     <SearchSection PlaceHolder="Search Characters, Islands or Objects"></SearchSection>
     <CommonItemsContainer ID="characterSection" title="Characters"></CommonItemsContainer>
     <CommonItemsContainer ID="islandSection" title="Islands"></CommonItemsContainer>
     <CommonItemsContainer ID="mistSection" title="Mist Objects"></CommonItemsContainer>
     
    </>
   
  );
}

export default App;

// task11-vue/one-piece-page/src/App.vue
<template>
  <div>
    <MenuContainer></MenuContainer>
    <MenuOptionsVue></MenuOptionsVue>
    <SinopsisContainerVue></SinopsisContainerVue>
    <SearchSectionVue PlaceHolder="Search Characters, Islands or Objects"></SearchSectionVue >
     <CommonItemsContainerVue ID="characterSection" title="Characters"></CommonItemsContainerVue>
     <CommonItemsContainerVue ID="islandSection" title="Islands"></CommonItemsContainerVue>
     <CommonItemsContainerVue ID="mistSection" title="Mist Objects"></CommonItemsContainerVue>

  </div>
  
</template>

<script>
import MenuContainer from './components/MenuContainer.vue'
import MenuOptionsVue from './components/MenuOptions.vue'
import SinopsisContainerVue from './components/SinopsisContainer.vue'
import SearchSectionVue from './components/SearchSection.vue'
import CommonItemsContainerVue from './components/CommonItemsContainer.vue'

export default {
  name: 'App',
  components: { MenuContainer,MenuOptionsVue,SinopsisContainerVue, SearchSectionVue,CommonItemsContainerVue  },

}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
