// task09-reactjs/one-piece-page/src/Components/CharactersContainerGridItem.js
import React, { Component } from 'react';

export default class CharactersContainerGridItem extends Component{
    constructor(props){
        super(props);
    }
    render(){
        return( <div className={`characters-container_grid_item ${this.props.show? '':'hideMore'}` }>
                    <img src={this.props.imgPath} alt="" />
                    <p className="characters-container_grid_item_characterName">
                        {this.props.name}
                    </p>
                </div>)
    }
}

// task11-vue/one-piece-page/src/components/CharactersContainerGridItem.vue
<template>
    <div class="characters-container_grid_item" :class="!mostrar && 'hideMore'">
        <img :src="imgPath" alt="" />
        <p className="characters-container_grid_item_characterName">{{text}}</p>
    </div>
</template>

<script>
    export default {
        name:"CharactersContainerGridItem",
        props:["text", "imgPath", "mostrar" ]
    }
</script>

<style scoped>

</style>
