// task09-reactjs/one-piece-page/src/Components/MenuContainer.js
import React, { Component } from 'react';
import menuIcon from '../images/menu.svg'
import opLogo from '../images/One-Piece-Logo 1.svg'
import closeMenu from '../images/close.svg'
export default class MenuContainer extends Component{

    constructor(props){
        super(props)
    }
    
    mostrarMenu = () => {
        let menuOptions = document.getElementById("menuOptions")
        let iconMenu = document.getElementById("iconMenu")
        if(window.getComputedStyle(menuOptions).display == 'none'){
            menuOptions.style.display = 'block';
            iconMenu.src =closeMenu;
        }
        else{
            menuOptions.style.display = 'none';
            iconMenu.src =menuIcon;
        }
    }
    render(){
        return(
            <div className="menu-container">
                <div className="menu-container_icon hideDesktop" onClick={this.mostrarMenu}>
                    <img id="iconMenu" src={menuIcon} alt="" />
                </div>
                <div className="menu-container_logo">
                    <img src={opLogo} alt="" />
                </div>
            </div>
        );
    }
}

// task11-vue/one-piece-page/src/components/MenuContainer.vue
<template>
    <div class="menu-container">
        <div class="menu-container_icon hideDesktop" v-on:click="mostrarMenu()" >
            <img id="iconMenu" src="../assets/menu.svg" alt="" />
        </div>
        <div class="menu-container_logo">
            <img src="../assets/One-Piece-Logo1.svg" alt="" />
        </div>
    </div>
</template>

<script>
    export default {
        name: "MenuContainer",
        methods:{
        mostrarMenu(){
        let menuOptions = document.getElementById("menuOptions")
        let iconMenu = document.getElementById("iconMenu")
        if(window.getComputedStyle(menuOptions).display == 'none'){
            menuOptions.style.display = 'block';
            iconMenu.src =require("../assets/close.svg");
        }
        else{
            menuOptions.style.display = 'none';
            iconMenu.src = require("../assets/menu.svg");
        }
    }
        }
    }
</script>
<style>
</style>
