// task09-reactjs/one-piece-page/src/Components/MenuItem.js
import React, { Component } from 'react';
import LanguagesItem from './LanguagesItem';
export default class MenuItem extends Component{
    constructor(props){
        super(props);
    }
    render(){
        if(this.props.link!==undefined)
            return <div className="menu_item"><a href={this.props.link}>{this.props.name}</a></div>
        else
            return (<div className="menu_item">
                {this.props.languages.map( (elem, index) => <LanguagesItem key={index} Language={elem}></LanguagesItem>)}
                </div>)
    }
}

// task11-vue/one-piece-page/src/components/MenuItem.vue
<template>
    <div v-if="text!==''" class="menu_item"><a :href="url">{{text}}</a></div>
    <div v-else class="menu_item">
        <LanguagesItemVue v-for="(language,index) in languages" :key="index" :text="language.name" :url="language.url"></LanguagesItemVue>      
    </div>
</template>

<script>
    import LanguagesItemVue from './LanguagesItem.vue'
    export default {
        name: "MenuItem",
        components:{LanguagesItemVue},
        props:["text", "url", "languages"]
    }
</script>

<style  scoped>

</style>
