// task09-reactjs/one-piece-page/src/Components/MenuOptions.js
import React, { Component } from 'react';
import MenuItem from './MenuItem';


export default class MenuOptions extends Component{
    render(){
        return(<div id="menuOptions" className="menu_items hideMenu">
                    {this.props.opciones.map( (elem, index) => <MenuItem key={index} name={elem.name} link={elem.link}></MenuItem>)}
                    <MenuItem key={4} languages={this.props.languages}></MenuItem>
                </div>
        )
    }
}

MenuOptions.defaultProps={
    opciones : [{
        name: "Home",
        link: "#"
    }, 
    {
        name: "Characters",
        link: "#characterSection"
    }, 
    {
        name: "Islands",
        link: "#islandSection"
    }, 
    {
        name: "Mist Objects",
        link: "#mistSection"
    }],
    languages: ["English", "Spanish"]
}

// task11-vue/one-piece-page/src/components/MenuOptions.vue
<template>
    <div id="menuOptions" className="menu_items hideMenu">
            <MenuItemVue v-for="(opcion,index) in opciones" :key="index" :text="opcion.name" :url="opcion.link" :languages="''"></MenuItemVue>
            <MenuItemVue  :text="''" :url="''" :languages="languages"></MenuItemVue>
    </div>
</template>

<script>
    import MenuItemVue from './MenuItem.vue'
    export default {
        name:"MenuOptions",
        components:{MenuItemVue},
        data(){
            return {
                opciones : [{
                    name: "Home",
                    link: "#"
                }, 
                {
                    name: "Characters",
                    link: "#characterSection"
                }, 
                {
                    name: "Islands",
                    link: "#islandSection"
                }, 
                {
                    name: "Mist Objects",
                    link: "#mistSection"
                }],
                languages:[
                    {
                        'name':"English",
                        'url':"../assets/usa.svg"
                    },
                    {
                        'name':"Spanish",
                        'url':"../assets/spain.svg"
                    }
                ]
            }
        }
    }
</script>

<style scoped>

</style>
