// task09-reactjs/one-piece-page/src/Components/SinopsisContainer.js
import React, { Component } from 'react';
import SinopsisContainerImage from './SinopsisContainerImage';
import SinopsisContainerReadMoreLogo from './SinopsisContainerReadMoreLogo'; 
import SinopsisContainerContent from './SinopsisContainerContent';

export default class SinopsisContainer extends Component{
    render(){
        return(<div className="sinopsis-container">
                    <SinopsisContainerImage></SinopsisContainerImage>
                    <SinopsisContainerReadMoreLogo></SinopsisContainerReadMoreLogo>
                    <SinopsisContainerContent></SinopsisContainerContent>
                </div>)
    }


}

// task11-vue/one-piece-page/src/components/SinopsisContainer.vue
<template>
    <div class="sinopsis-container">
                    <SinopsisContainerImageVue></SinopsisContainerImageVue>
                    <SinopsisContainerReadMoreLogoVue></SinopsisContainerReadMoreLogoVue>
                    <SinopsisContainerContentVue></SinopsisContainerContentVue>
                </div>
</template>

<script>
    import SinopsisContainerImageVue from './SinopsisContainerImage.vue'
    import SinopsisContainerReadMoreLogoVue from './SinopsisContainerReadMoreLogo.vue'
    import SinopsisContainerContentVue from './SinopsisContainerContent.vue'
    export default {
        name:"SinopsisContainer",
        components:{SinopsisContainerImageVue, SinopsisContainerReadMoreLogoVue, SinopsisContainerContentVue}
    }
</script>

<style scoped>

</style>
