// task09-reactjs/one-piece-page/src/Components/SinopsisContainerContent.js
import React, { Component } from 'react';
import SinopsisContainerContentTitle from './SinopsisContainerContentTitle'; 
import SinopsisContainerContentText from './SinopsisContainerContentText'; 
import SinopsisContainerContentReadAll from './SinopsisContainerContentReadAll';

export default class SinopsisContainerContent extends Component{
    render(){
        return(<div className="sinopsis-container_content">
                <SinopsisContainerContentTitle title="Sipnosis"/>
                <SinopsisContainerContentText/>
                <div className="division hideDesktop"></div>
                <SinopsisContainerContentReadAll/>
               </div>)
    }
}

// task11-vue/one-piece-page/src/components/SinopsisContainerContent.vue
<template>
    <div class="sinopsis-container_content">
        <SinopsisContainerContentTitleVue title="Sipnosis"></SinopsisContainerContentTitleVue>
        <SinopsisContainerContentTextVue></SinopsisContainerContentTextVue>
        <div class="division hideDesktop"></div>
        <SinopsisContainerContentReadAllVue ></SinopsisContainerContentReadAllVue>
    </div>
</template>

<script>
    import SinopsisContainerContentReadAllVue from './SinopsisContainerContentReadAll.vue'
    import SinopsisContainerContentTextVue from './SinopsisContainerContentText.vue'
    import SinopsisContainerContentTitleVue from './SinopsisContainerContentTitle.vue'
    export default {
        name:"SinopsisContainerContent", 
        components:{SinopsisContainerContentReadAllVue, SinopsisContainerContentTextVue, SinopsisContainerContentTitleVue}
    }
</script>

<style scoped>

</style>
